//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.07.10 at 12:45:26 PM CEST
//
// TOSCA version: TOSCA-v1.0-cs02.xsd
//

package org.opentosca.model.tosca;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.opentosca.model.tosca package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements IToscaModelFactory {
	
	private final static QName _Documentation_QNAME = new QName("http://docs.oasis-open.org/tosca/ns/2011/12", "documentation");
	
	
	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.opentosca.model.tosca
	 * 
	 */
	public ObjectFactory() {
	}
	
	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TDefinitions }
	 *
	 */
	@Override
	public TDefinitions createTDefinitions() {
		return new TDefinitions();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipTemplate }
	 *
	 */
	@Override
	public TRelationshipTemplate createTRelationshipTemplate() {
		return new TRelationshipTemplate();
	}

	/**
	 * Create an instance of
	 * {@link org.opentosca.model.tosca.TRelationshipTemplate.RelationshipConstraints }
	 *
	 */
	@Override
	public TRelationshipTemplate.RelationshipConstraints createTRelationshipTemplateRelationshipConstraints() {
		return new TRelationshipTemplate.RelationshipConstraints();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRequirementDefinition }
	 *
	 */
	@Override
	public TRequirementDefinition createTRequirementDefinition() {
		return new TRequirementDefinition();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeTemplate }
	 *
	 */
	@Override
	public TNodeTemplate createTNodeTemplate() {
		return new TNodeTemplate();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TTopologyElementInstanceStates }
	 *
	 */
	@Override
	public TTopologyElementInstanceStates createTTopologyElementInstanceStates() {
		return new TTopologyElementInstanceStates();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TAppliesTo }
	 *
	 */
	@Override
	public TAppliesTo createTAppliesTo() {
		return new TAppliesTo();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TImplementationArtifacts }
	 *
	 */
	@Override
	public TImplementationArtifacts createTImplementationArtifacts() {
		return new TImplementationArtifacts();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TArtifactReference }
	 *
	 */
	@Override
	public TArtifactReference createTArtifactReference() {
		return new TArtifactReference();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TBoundaryDefinitions }
	 *
	 */
	@Override
	public TBoundaryDefinitions createTBoundaryDefinitions() {
		return new TBoundaryDefinitions();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TBoundaryDefinitions.Properties }
	 *
	 */
	@Override
	public TBoundaryDefinitions.Properties createTBoundaryDefinitionsProperties() {
		return new TBoundaryDefinitions.Properties();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TExportedOperation }
	 *
	 */
	@Override
	public TExportedOperation createTExportedOperation() {
		return new TExportedOperation();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPlan }
	 *
	 */
	@Override
	public TPlan createTPlan() {
		return new TPlan();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TCapabilityDefinition }
	 *
	 */
	@Override
	public TCapabilityDefinition createTCapabilityDefinition() {
		return new TCapabilityDefinition();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TOperation }
	 *
	 */
	@Override
	public TOperation createTOperation() {
		return new TOperation();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TArtifactTemplate }
	 *
	 */
	@Override
	public TArtifactTemplate createTArtifactTemplate() {
		return new TArtifactTemplate();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipTypeImplementation }
	 *
	 */
	@Override
	public TRelationshipTypeImplementation createTRelationshipTypeImplementation() {
		return new TRelationshipTypeImplementation();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipType }
	 *
	 */
	@Override
	public TRelationshipType createTRelationshipType() {
		return new TRelationshipType();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeTypeImplementation }
	 *
	 */
	@Override
	public TNodeTypeImplementation createTNodeTypeImplementation() {
		return new TNodeTypeImplementation();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeType }
	 *
	 */
	@Override
	public TNodeType createTNodeType() {
		return new TNodeType();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TDocumentation }
	 *
	 */
	@Override
	public TDocumentation createTDocumentation() {
		return new TDocumentation();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.Definitions }
	 *
	 */
	@Override
	public org.opentosca.model.tosca.Definitions createDefinitions() {
		return new Definitions();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TExtensibleElements }
	 *
	 */
	@Override
	public TExtensibleElements createTExtensibleElements() {
		return new TExtensibleElements();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TDefinitions.Extensions }
	 *
	 */
	@Override
	public TDefinitions.Extensions createTDefinitionsExtensions() {
		return new TDefinitions.Extensions();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TImport }
	 *
	 */
	@Override
	public TImport createTImport() {
		return new TImport();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TDefinitions.Types }
	 *
	 */
	@Override
	public TDefinitions.Types createTDefinitionsTypes() {
		return new TDefinitions.Types();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TServiceTemplate }
	 *
	 */
	@Override
	public TServiceTemplate createTServiceTemplate() {
		return new TServiceTemplate();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRequirementType }
	 *
	 */
	@Override
	public TRequirementType createTRequirementType() {
		return new TRequirementType();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TCapabilityType }
	 *
	 */
	@Override
	public TCapabilityType createTCapabilityType() {
		return new TCapabilityType();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TArtifactType }
	 *
	 */
	@Override
	public TArtifactType createTArtifactType() {
		return new TArtifactType();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPolicyType }
	 *
	 */
	@Override
	public TPolicyType createTPolicyType() {
		return new TPolicyType();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPolicyTemplate }
	 *
	 */
	@Override
	public TPolicyTemplate createTPolicyTemplate() {
		return new TPolicyTemplate();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRequirementRef }
	 *
	 */
	@Override
	public TRequirementRef createTRequirementRef() {
		return new TRequirementRef();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TImplementationArtifact }
	 *
	 */
	@Override
	public TImplementationArtifact createTImplementationArtifact() {
		return new TImplementationArtifact();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TParameter }
	 *
	 */
	@Override
	public TParameter createTParameter() {
		return new TParameter();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TExtension }
	 *
	 */
	@Override
	public TExtension createTExtension() {
		return new TExtension();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TDeploymentArtifact }
	 *
	 */
	@Override
	public TDeploymentArtifact createTDeploymentArtifact() {
		return new TDeploymentArtifact();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRequiredContainerFeatures }
	 *
	 */
	@Override
	public TRequiredContainerFeatures createTRequiredContainerFeatures() {
		return new TRequiredContainerFeatures();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TExportedInterface }
	 *
	 */
	@Override
	public TExportedInterface createTExportedInterface() {
		return new TExportedInterface();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TConstraint }
	 *
	 */
	@Override
	public TConstraint createTConstraint() {
		return new TConstraint();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPlans }
	 *
	 */
	@Override
	public TPlans createTPlans() {
		return new TPlans();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPropertyMapping }
	 *
	 */
	@Override
	public TPropertyMapping createTPropertyMapping() {
		return new TPropertyMapping();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TCondition }
	 *
	 */
	@Override
	public TCondition createTCondition() {
		return new TCondition();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TExtensions }
	 *
	 */
	@Override
	public TExtensions createTExtensions() {
		return new TExtensions();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TTopologyTemplate }
	 *
	 */
	@Override
	public TTopologyTemplate createTTopologyTemplate() {
		return new TTopologyTemplate();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TTags }
	 *
	 */
	@Override
	public TTags createTTags() {
		return new TTags();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPolicy }
	 *
	 */
	@Override
	public TPolicy createTPolicy() {
		return new TPolicy();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRequiredContainerFeature }
	 *
	 */
	@Override
	public TRequiredContainerFeature createTRequiredContainerFeature() {
		return new TRequiredContainerFeature();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TDeploymentArtifacts }
	 *
	 */
	@Override
	public TDeploymentArtifacts createTDeploymentArtifacts() {
		return new TDeploymentArtifacts();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TCapability }
	 *
	 */
	@Override
	public TCapability createTCapability() {
		return new TCapability();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPropertyConstraint }
	 *
	 */
	@Override
	public TPropertyConstraint createTPropertyConstraint() {
		return new TPropertyConstraint();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TTag }
	 *
	 */
	@Override
	public TTag createTTag() {
		return new TTag();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TInterface }
	 *
	 */
	@Override
	public TInterface createTInterface() {
		return new TInterface();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRequirement }
	 *
	 */
	@Override
	public TRequirement createTRequirement() {
		return new TRequirement();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TCapabilityRef }
	 *
	 */
	@Override
	public TCapabilityRef createTCapabilityRef() {
		return new TCapabilityRef();
	}

	/**
	 * Create an instance of
	 * {@link org.opentosca.model.tosca.TEntityTemplate.Properties }
	 *
	 */
	@Override
	public org.opentosca.model.tosca.TEntityTemplate.Properties createTEntityTemplateProperties() {
		return new org.opentosca.model.tosca.TEntityTemplate.Properties();
	}

	/**
	 * Create an instance of
	 * {@link org.opentosca.model.tosca.TEntityTemplate.PropertyConstraints }
	 *
	 */
	@Override
	public org.opentosca.model.tosca.TEntityTemplate.PropertyConstraints createTEntityTemplatePropertyConstraints() {
		return new org.opentosca.model.tosca.TEntityTemplate.PropertyConstraints();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipTemplate.SourceElement }
	 *
	 */
	@Override
	public TRelationshipTemplate.SourceElement createTRelationshipTemplateSourceElement() {
		return new TRelationshipTemplate.SourceElement();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipTemplate.TargetElement }
	 *
	 */
	@Override
	public TRelationshipTemplate.TargetElement createTRelationshipTemplateTargetElement() {
		return new TRelationshipTemplate.TargetElement();
	}

	/**
	 * Create an instance of
	 * {@link org.opentosca.model.tosca.TRelationshipTemplate.RelationshipConstraints.RelationshipConstraint }
	 *
	 */
	@Override
	public TRelationshipTemplate.RelationshipConstraints.RelationshipConstraint createTRelationshipTemplateRelationshipConstraintsRelationshipConstraint() {
		return new TRelationshipTemplate.RelationshipConstraints.RelationshipConstraint();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRequirementDefinition.Constraints }
	 *
	 */
	@Override
	public TRequirementDefinition.Constraints createTRequirementDefinitionConstraints() {
		return new TRequirementDefinition.Constraints();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeTemplate.Requirements }
	 *
	 */
	@Override
	public TNodeTemplate.Requirements createTNodeTemplateRequirements() {
		return new TNodeTemplate.Requirements();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeTemplate.Capabilities }
	 *
	 */
	@Override
	public TNodeTemplate.Capabilities createTNodeTemplateCapabilities() {
		return new TNodeTemplate.Capabilities();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeTemplate.Policies }
	 *
	 */
	@Override
	public TNodeTemplate.Policies createTNodeTemplatePolicies() {
		return new TNodeTemplate.Policies();
	}

	/**
	 * Create an instance of
	 * {@link org.opentosca.model.tosca.TTopologyElementInstanceStates.InstanceState }
	 *
	 */
	@Override
	public TTopologyElementInstanceStates.InstanceState createTTopologyElementInstanceStatesInstanceState() {
		return new TTopologyElementInstanceStates.InstanceState();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TAppliesTo.NodeTypeReference }
	 *
	 */
	@Override
	public TAppliesTo.NodeTypeReference createTAppliesToNodeTypeReference() {
		return new TAppliesTo.NodeTypeReference();
	}

	/**
	 * Create an instance of
	 * {@link org.opentosca.model.tosca.TImplementationArtifacts.ImplementationArtifact }
	 *
	 */
	@Override
	public TImplementationArtifacts.ImplementationArtifact createTImplementationArtifactsImplementationArtifact() {
		return new TImplementationArtifacts.ImplementationArtifact();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TArtifactReference.Include }
	 *
	 */
	@Override
	public TArtifactReference.Include createTArtifactReferenceInclude() {
		return new TArtifactReference.Include();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TArtifactReference.Exclude }
	 *
	 */
	@Override
	public TArtifactReference.Exclude createTArtifactReferenceExclude() {
		return new TArtifactReference.Exclude();
	}

	/**
	 * Create an instance of
	 * {@link org.opentosca.model.tosca.TEntityType.DerivedFrom }
	 *
	 */
	@Override
	public org.opentosca.model.tosca.TEntityType.DerivedFrom createTEntityTypeDerivedFrom() {
		return new org.opentosca.model.tosca.TEntityType.DerivedFrom();
	}

	/**
	 * Create an instance of
	 * {@link org.opentosca.model.tosca.TEntityType.PropertiesDefinition }
	 *
	 */
	@Override
	public org.opentosca.model.tosca.TEntityType.PropertiesDefinition createTEntityTypePropertiesDefinition() {
		return new org.opentosca.model.tosca.TEntityType.PropertiesDefinition();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TBoundaryDefinitions.PropertyConstraints }
	 *
	 */
	@Override
	public TBoundaryDefinitions.PropertyConstraints createTBoundaryDefinitionsPropertyConstraints() {
		return new TBoundaryDefinitions.PropertyConstraints();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TBoundaryDefinitions.Requirements }
	 *
	 */
	@Override
	public TBoundaryDefinitions.Requirements createTBoundaryDefinitionsRequirements() {
		return new TBoundaryDefinitions.Requirements();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TBoundaryDefinitions.Capabilities }
	 *
	 */
	@Override
	public TBoundaryDefinitions.Capabilities createTBoundaryDefinitionsCapabilities() {
		return new TBoundaryDefinitions.Capabilities();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TBoundaryDefinitions.Policies }
	 *
	 */
	@Override
	public TBoundaryDefinitions.Policies createTBoundaryDefinitionsPolicies() {
		return new TBoundaryDefinitions.Policies();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TBoundaryDefinitions.Interfaces }
	 *
	 */
	@Override
	public TBoundaryDefinitions.Interfaces createTBoundaryDefinitionsInterfaces() {
		return new TBoundaryDefinitions.Interfaces();
	}

	/**
	 * Create an instance of
	 * {@link org.opentosca.model.tosca.TBoundaryDefinitions.Properties.PropertyMappings }
	 *
	 */
	@Override
	public TBoundaryDefinitions.Properties.PropertyMappings createTBoundaryDefinitionsPropertiesPropertyMappings() {
		return new TBoundaryDefinitions.Properties.PropertyMappings();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TExportedOperation.NodeOperation }
	 *
	 */
	@Override
	public TExportedOperation.NodeOperation createTExportedOperationNodeOperation() {
		return new TExportedOperation.NodeOperation();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TExportedOperation.RelationshipOperation }
	 *
	 */
	@Override
	public TExportedOperation.RelationshipOperation createTExportedOperationRelationshipOperation() {
		return new TExportedOperation.RelationshipOperation();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TExportedOperation.Plan }
	 *
	 */
	@Override
	public TExportedOperation.Plan createTExportedOperationPlan() {
		return new TExportedOperation.Plan();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPlan.InputParameters }
	 *
	 */
	@Override
	public TPlan.InputParameters createTPlanInputParameters() {
		return new TPlan.InputParameters();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPlan.OutputParameters }
	 *
	 */
	@Override
	public TPlan.OutputParameters createTPlanOutputParameters() {
		return new TPlan.OutputParameters();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPlan.PlanModel }
	 *
	 */
	@Override
	public TPlan.PlanModel createTPlanPlanModel() {
		return new TPlan.PlanModel();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TPlan.PlanModelReference }
	 *
	 */
	@Override
	public TPlan.PlanModelReference createTPlanPlanModelReference() {
		return new TPlan.PlanModelReference();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TCapabilityDefinition.Constraints }
	 *
	 */
	@Override
	public TCapabilityDefinition.Constraints createTCapabilityDefinitionConstraints() {
		return new TCapabilityDefinition.Constraints();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TOperation.InputParameters }
	 *
	 */
	@Override
	public TOperation.InputParameters createTOperationInputParameters() {
		return new TOperation.InputParameters();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TOperation.OutputParameters }
	 *
	 */
	@Override
	public TOperation.OutputParameters createTOperationOutputParameters() {
		return new TOperation.OutputParameters();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TArtifactTemplate.ArtifactReferences }
	 *
	 */
	@Override
	public TArtifactTemplate.ArtifactReferences createTArtifactTemplateArtifactReferences() {
		return new TArtifactTemplate.ArtifactReferences();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipTypeImplementation.DerivedFrom }
	 *
	 */
	@Override
	public TRelationshipTypeImplementation.DerivedFrom createTRelationshipTypeImplementationDerivedFrom() {
		return new TRelationshipTypeImplementation.DerivedFrom();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipType.SourceInterfaces }
	 *
	 */
	@Override
	public TRelationshipType.SourceInterfaces createTRelationshipTypeSourceInterfaces() {
		return new TRelationshipType.SourceInterfaces();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipType.TargetInterfaces }
	 *
	 */
	@Override
	public TRelationshipType.TargetInterfaces createTRelationshipTypeTargetInterfaces() {
		return new TRelationshipType.TargetInterfaces();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipType.ValidSource }
	 *
	 */
	@Override
	public TRelationshipType.ValidSource createTRelationshipTypeValidSource() {
		return new TRelationshipType.ValidSource();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TRelationshipType.ValidTarget }
	 *
	 */
	@Override
	public TRelationshipType.ValidTarget createTRelationshipTypeValidTarget() {
		return new TRelationshipType.ValidTarget();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeTypeImplementation.DerivedFrom }
	 *
	 */
	@Override
	public TNodeTypeImplementation.DerivedFrom createTNodeTypeImplementationDerivedFrom() {
		return new TNodeTypeImplementation.DerivedFrom();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeType.RequirementDefinitions }
	 *
	 */
	@Override
	public TNodeType.RequirementDefinitions createTNodeTypeRequirementDefinitions() {
		return new TNodeType.RequirementDefinitions();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeType.CapabilityDefinitions }
	 *
	 */
	@Override
	public TNodeType.CapabilityDefinitions createTNodeTypeCapabilityDefinitions() {
		return new TNodeType.CapabilityDefinitions();
	}

	/**
	 * Create an instance of {@link org.opentosca.model.tosca.TNodeType.Interfaces }
	 *
	 */
	@Override
	public TNodeType.Interfaces createTNodeTypeInterfaces() {
		return new TNodeType.Interfaces();
	}

	/**
	 * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link org.opentosca.model.tosca.TDocumentation }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://docs.oasis-open.org/tosca/ns/2011/12", name = "documentation")
	public JAXBElement<TDocumentation> createDocumentation(TDocumentation value) {
		return new JAXBElement<TDocumentation>(_Documentation_QNAME, TDocumentation.class, null, value);
	}
	
}
